class ValidationException(Exception):
    def __init__(self, message):
        self.message = message
        super().__init__(self.message)
    
# Do not edit this file
# This is a custom exception class that inherits from the built-in `Exception` class. 
# It takes a single parameter, `message`. Line 4 INVOKES the __init__  method of base class 
# (note: the parantheses) and passes the error message to it.